name: Greeting from Github

on: push

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
    - run:
        echo 'Hello!'.
  my-second-job:
    name: My second Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: My name is
        FIRST_NAME: John
        LAST_NAME: Doe
      run: |
        echo $MY_VAR $FIRST_NAME $LAST_NAME.
        echo 'This is the first workflow we created'.
