name: Greeting from Github

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: John
        LAST_NAME: Doe
      run: |
        echo $MY_VAR $FIRST_NAME $LAST_NAME.
